### PR TITLE
Protobuf update

### PR DESCRIPTION
**Pull request by nlf**
This update is to leverage the recently refactored protobuf.js. Performance and functionality remain roughly the same, but maintainability will be vastly improved.

All current tests pass, with the only noticeable difference being that counters (which use a 64 bit data type) will now be returned as [long](https://github.com/dcodeIO/Long.js) values instead of plain numbers, to preserve their 64 bit length.

### CODE REVIEW

**Comment by nlf** [comment]
Also note that travis builds are failing because of the same out-of-order sorted key response issue we've been having in other builds.

**Comment by oleksiyk** [comment]
The out-of-order keys response can be fixed by adding `pagination_sort` param like here: https://github.com/oleksiyk/riakpbc/commit/4579b61167ff6113af189179b2c15f091ef7b75b

**Comment by nlf** [comment]
@oleksiyk good catch! thanks. we have passing builds again, at last!

**Comment by nisaacson** [comment]
:+1: Nice to have passing builds. 

Is the `pagination_sort`option documented anywhere? I couldn't find it listed in the Basho Riak docs

**Comment by oleksiyk** [comment]
I've found it in the recent riak_kv.proto: https://github.com/basho/riak_pb/blob/develop/src/riak_kv.proto#L183

**Comment by nlf** [comment]
Yeah, documentation around the protocol buffer interface is pretty lacking. I'm debating generating some better documentation for the readme and basing it directly off the proto files rather than linking to basho's docs. Thoughts?

**Pull request merged**
