### PR TITLE
Change: use docker to provision riak in vagrant.

### PR DESCRIPTION
**Pull request by nisaacson**
Add: support for vmware_fusion provider as well as virtualbox in Vagrantfile.
Rebuild binary modules in vagrant vm during provisioning.

### CODE REVIEW

**Comment by nlf** [comment]
I'm not totally sure what this achieves.. Will this create a new vagrant box that has docker installed in it, and install your docker container within that image?

**Comment by nisaacson** [comment]
Correct, this way it is easy to blow away the existing data in riak and start fresh just by restarting the docker container. 

It also makes provisioning the vagrant vm simpler since riak does not need to be installed on the bare metal virtual machine but instead runs inside a docker container

**Comment by nlf** [comment]
in that case :+1:

**Comment by nisaacson** [comment]
And with this setup developers do not need to install riak on their host machines to test changes to the code.

**Pull request merged**
