### PR TITLE
Fix possible buffer memory overlap in _receive

### PR DESCRIPTION
**Pull request by oleksiyk**
_receive() should return a copy  of the collected response data to avoid possible memory overlap (my fault, it was introduced in https://github.com/nlf/riakpbc/pull/50)

### CODE REVIEW

**Comment by nlf** [comment]
I'm not completely sure what you're solving here, aside from allocating a new buffer and copying the data in to that for the next function call. Were you able to prove that there's actually an overlap somewhere?

**Comment by oleksiyk** [comment]
Here https://github.com/nlf/riakpbc/blob/master/lib/connection-manager.js#L119 we send a slice of the buffer for further processing. Before that we set readBufPos=0. If the code in `recieve` handler is doing anything asynchronously it will be possible for the next data from network buffer to overwrite original `readBuffer` and the slice we sent. This happens with `string` and `bytes` field types because protobuf.js doesn't copy them but uses `slice` again.

**Comment by oleksiyk** [comment]
This can also be fixed here: https://github.com/nlf/protobuf.js/blob/master/index.js#L103 if we copy the data instead of slicing it. But its better to handle this situation in connection manager.

**Comment by oleksiyk** [comment]
Ah, and yes - I actually experienced this problem. I was reading large amounts of binary data (from different keys) and eventually the buffer I received from `get` as `reply.content[0].value` was overwritten during its asynchronous processing.

**Comment by nlf** [comment]
hmm.. I see what you mean. Since riakpbc is the only thing really using protobuf.js (that I know of) and it's receive handler doesn't do anything async, it's never come up as an issue.

I intentionally avoided allocating new buffers where ever possible because it's not exactly a fast operation. As things currently are, with nothing async happening, it's probably fine.

I would definitely contend that if this is something worth fixing, it should be done in protobuf.js since that's the real problem (i.e. someone else could be using it and doing async operations in their receive handler).

**Comment by nlf** [comment]
You beat me with that last comment. Let's close this one and fix it in protobuf.js instead, so it takes care of it there instead of adding a work around here.

**Comment by oleksiyk** [comment]
ok, i'll create a PR in protobuf.js

**Pull request closed without merging**
