### PR TITLE
Updated riak_pb spec loader

### PR DESCRIPTION
**Pull request by oleksiyk**
This patch will make it easier to update riak_pb source .proto files. It will also load message codes from a csv file (also easy copied from https://github.com/basho/riak_pb/tree/develop/src). 
Also included are the latest .proto files.

### CODE REVIEW

**Comment by oleksiyk** [comment]
This patch requires updated protobuf.js: https://github.com/nlf/protobuf.js/pull/9

**Comment by nlf** [comment]
While I appreciate the effort behind this, protobuf.js and the proto loader are both undergoing some pretty major refactors right now anyway. Using the CSV for message codes is a great idea though. I'll go ahead and implement that as part of the [nlf/riakproto](https://github.com/nlf/riakproto) package, which is where the proto files will exist. That package is simply a proto -> json converter that riakpbc will depend on for simplicity's sake.

Protobuf.js is also being updated to use proto files as parsed by [proto2json](https://github.com/Sannis/node-proto2json) rather than the raw files, as well as being rewritten to be more maintainable.

**Comment by nlf** [comment]
Actually, I just realized that the CSV file and the new proto files are for riak 2.0.0. I'm keeping the main branch of this project focused on 1.4 until 2.0 goes final. I will, however, create a new major version in a separate branch to track riak 2.0 changes.

**Comment by oleksiyk** [comment]
Ok, are there any estimation dates? I was going to update my fork of riakpbc to riak 2.0 in the nearest days. Mostly search of course.

**Comment by nlf** [comment]
I can have it ready on Monday.

**Comment by oleksiyk** [comment]
Great! Thanks!

**Pull request closed without merging**
