### PR TITLE
Streaming 2i

### PR DESCRIPTION
**Pull request by nisaacson**
Added a missing streaming interface to the client api for secondary index queries

### CODE REVIEW

**Comment by nlf** [comment]
This looks great. Good catch, and thanks for fixing it. Any interest in becoming a maintainer on the project?

**Comment by nisaacson** [comment]
thanks for merging this in so quickly. Can you do a version bump and publish to npm?

``` bash
npm version patch
npm publish
git push --tags
```

**Comment by nisaacson** [comment]
I would be happy to be added as a maintainer

**Comment by nlf** [comment]
Just did, version 0.1.1 is published with this merged

**Comment by nlf** [comment]
And I've added you as a collaborator on the repo. Is your username on npm the same as github? I can add you there as well.

**Comment by nisaacson** [comment]
yes, I am nisaacson on npm as well

**Comment by nlf** [comment]
you're added on npm now too :) also, fyi I'm looking in to the other issue you filed right now

**Pull request merged**
