### PR TITLE
grow buffer if chunk have great size

### PR DESCRIPTION
**Pull request by ahiipsa**

### CODE REVIEW

**Comment by nlf** [comment]
Can you write a test that shows what this fixes?

**Comment by ahiipsa** [comment]
It happening in one WiFi point (macmini share)
Not called callback function or event "end".

``` javascript
client.mapred(options, function(err, response) {   });
// or 
client.mapred(options, function(err, response) {});
client.on('end', function(){ });
```

The problem occurs, if message "end data"  ({done: true}) sent in tail last chunk. I don't know how to emulate this behavior for test.

_receive create buffer with size for last package, ignores that the size of the next chunk could be bigger

``` javascript
// Chunk in hex;
    // work
    var chunks = [];
    chunks.push("000008bb18080212b5115b227b5c2269645c223a5c2231333632373837312d383731392d346631322d613331652d6463393935393631386431365c222c5c226e616d655c223a5c22315c75303431375c75303433325c75303433355c75303433375c75303433345c75303433645c75303434625c7530343335205c75303433325c75303433655c75303433395c75303433645c75303434623a205c75303432645c75303433665c75303433385c75303433375c75303433655c75303433342031205c7532303133205c75303432315c75303433615c75303434305c75303434625c75303434325c75303433305c7530343466205c75303434335c75303433335c75303434305c75303433655c75303433375c75303433305c222c5c226f726967696e4e616d655c223a5c225c222c5c2273686f727449645c223a302c5c226465736372697074696f6e5c223a5c225c75303431635c75303433385c75303434305c75303433645c75303433305c7530343466205c7530343338205c75303433665c75303434305c75303433655c75303434365c75303433325c75303433355c75303434325c75303433305c75303434655c75303434395c75303433305c7530343466205c75303433665c75303433625c75303433305c75303433645c75303433355c75303434325c7530343330205c75303431645c75303433305c75303433315c75303434332e205c75303432325c75303433655c75303434305c75303433335c75303433655c75303433325c75303433305c7530343466205c75303434345c75303433355c75303433345c75303433355c75303434305c75303433305c75303434365c75303433385c75303434662c205c75303433645c7530343335205c75303433365c75303433355c75303433625c75303433305c7530343466205c75303433665c75303433625c75303433305c75303434325c75303433385c75303434325c7530343463205c75303433645c75303433305c75303433625c75303433655c75303433335c75303433382c205c75303433325c75303434315c75303434325c75303434335c75303433665c75303433305c75303433355c7530343432205c7530343332205c75303433665c75303434305c75303434665c75303433635c75303433655c7530343339205c75303433615c75303433655c75303433645c75303434345c75303433625c75303433385c75303433615c7530343432205c7530343431205c75303433615c75303433655c75303434305c75303433655c75303433625c75303433355c75303433325c75303433655c7530343339205c75303431305c75303433635c75303433385c75303433345c75303433305c75303433625c75303433655c75303433392c205c75303433665c75303434305c75303433305c75303433325c75303434665c75303434395c75303433355c7530343339205c75303433645c7530343330205c75303433665c75303433625c75303433305c75303433645c75303433355c75303434325c75303433352c205c75303434375c75303434325c7530343365205c75303433665c75303434305c75303433385c75303433325c75303433655c75303433345c75303433385c7530343432205c7530343361205c75303433325c75303433655c75303433395c75303433645c75303433352e205c75303431645c7530343330205c75303434315c75303434325c75303433655c75303434305c75303433655c75303433645c7530343335205c75303433615c75303433655c75303434305c75303433655c75303433625c75303433355c75303433325c7530343462205c7530343338205c75303434305c75303433355c75303434315c75303433665c75303434335c75303433315c75303433625c75303433385c75303433615c7530343338205c7530343332205c75303433645c75303433355c7530343339205c75303434335c75303434375c75303433305c75303434315c75303434325c75");
    chunks.push("303433325c75303434335c75303434655c7530343432205c75303433345c75303433325c7530343330205c75303434305c75303434625c75303434365c75303433305c75303434305c75303434662d5c75303433345c75303433365c75303433355c75303433345c75303433305c75303434663a205c75303434335c75303434375c75303433385c75303434325c75303433355c75303433625c7530343463205c7530343338205c75303434335c75303434375c75303433355c75303433645c75303433385c75303433612c205c75303431615c75303433325c75303433305c75303433392d5c75303431335c75303433655c75303433642d5c75303431345c75303433365c75303433385c7530343364205c7530343338205c75303431655c75303433315c75303433382d5c75303431325c75303433305c7530343364205c75303431615c75303433355c75303433645c75303433655c75303433315c75303433385c75323032365c222c5c22796561725c223a313939392c5c226167655265737472696374696f6e5c223a302c5c226469726563746f72735c223a5b5c2247656f726765204c756361735c225d2c5c226163746f72735c223a5b5c224d61726b2048616d696c6c5c222c5c224861727269736f6e20466f72645c222c5c22436172726965204669736865725c225d2c5c226475726174696f6e5c223a3131342c5c22636f756e74726965735c223a5b5c225553415c225d2c5c22726174696e675c223a7b5c226b696e6f706f69736b5c223a382e372c5c22696d64625c223a382e377d2c5c2273747265616d735c223a7b5c226d6f7669655c223a5c225c222c5c22747261696c65725c223a5c225c227d2c5c22636174616c6f67735c223a5b5d2c5c2264617465437265617465645c223a5c22323031342d31302d30315431323a30353a32342e3334385a5c222c5c22696d646249645c223a5c225c222c5c226b696e6f706f69736b49645c223a5c225c222c5c227075626c69736865645c223a66616c73652c5c227265636f6d6d656e645c223a747275652c5c226d6f64656c547970655c223a5c226d6f7669655c227d225d");
    chunks.push("00000003181801");

    // not work
    var chunks2 = [];
    chunks.push("000008bb18080212b5115b227b5c2269645c223a5c2231333632373837312d383731392d346631322d613331652d6463393935393631386431365c222c5c226e616d655c223a5c22315c75303431375c75303433325c75303433355c75303433375c75303433345c75303433645c75303434625c7530343335205c75303433325c75303433655c75303433395c75303433645c75303434623a205c75303432645c75303433665c75303433385c75303433375c75303433655c75303433342031205c7532303133205c75303432315c75303433615c75303434305c75303434625c75303434325c75303433305c7530343466205c75303434335c75303433335c75303434305c75303433655c75303433375c75303433305c222c5c226f726967696e4e616d655c223a5c225c222c5c2273686f727449645c223a302c5c226465736372697074696f6e5c223a5c225c75303431635c75303433385c75303434305c75303433645c75303433305c7530343466205c7530343338205c75303433665c75303434305c75303433655c75303434365c75303433325c75303433355c75303434325c75303433305c75303434655c75303434395c75303433305c7530343466205c75303433665c75303433625c75303433305c75303433645c75303433355c75303434325c7530343330205c75303431645c75303433305c75303433315c75303434332e205c75303432325c75303433655c75303434305c75303433335c75303433655c75303433325c75303433305c7530343466205c75303434345c75303433355c75303433345c75303433355c75303434305c75303433305c75303434365c75303433385c75303434662c205c75303433645c7530343335205c75303433365c75303433355c75303433625c75303433305c7530343466205c75303433665c75303433625c75303433305c75303434325c75303433385c75303434325c7530343463205c75303433645c75303433305c75303433625c75303433655c75303433335c75303433382c205c75303433325c75303434315c75303434325c75303434335c75303433665c75303433305c75303433355c7530343432205c7530343332205c75303433665c75303434305c75303434665c75303433635c75303433655c7530343339205c75303433615c75303433655c75303433645c75303434345c75303433625c75303433385c75303433615c7530343432205c7530343431205c75303433615c75303433655c75303434305c75303433655c75303433625c75303433355c75303433325c75303433655c7530343339205c75303431305c75303433635c75303433385c75303433345c75303433305c75303433625c75303433655c75303433392c205c75303433665c75303434305c75303433305c75303433325c75303434665c75303434395c75303433355c7530343339205c75303433645c7530343330205c75303433665c75303433625c75303433305c75303433645c75303433355c75303434325c75303433352c205c75303434375c75303434325c7530343365205c75303433665c75303434305c75303433385c75303433325c75303433655c75303433345c75303433385c7530343432205c7530343361205c75303433325c75303433655c75303433395c75303433645c75303433352e205c75303431645c7530343330205c75303434315c75303434325c75303433655c75303434305c75303433655c75303433645c7530343335205c75303433615c75303433655c75303434305c75303433655c75303433625c75303433355c75303433325c7530343462205c7530343338205c75303434305c75303433355c75303434315c75303433665c75303434335c75303433315c75303433625c75303433385c75303433615c7530343338205c7530343332205c75303433645c75303433355c7530343339205c75303434335c75303434375c75303433305c75303434315c75303434325c75");
    chunks.push("303433325c75303434335c75303434655c7530343432205c75303433345c75303433325c7530343330205c75303434305c75303434625c75303434365c75303433305c75303434305c75303434662d5c75303433345c75303433365c75303433355c75303433345c75303433305c75303434663a205c75303434335c75303434375c75303433385c75303434325c75303433355c75303433625c7530343463205c7530343338205c75303434335c75303434375c75303433355c75303433645c75303433385c75303433612c205c75303431615c75303433325c75303433305c75303433392d5c75303431335c75303433655c75303433642d5c75303431345c75303433365c75303433385c7530343364205c7530343338205c75303431655c75303433315c75303433382d5c75303431325c75303433305c7530343364205c75303431615c75303433355c75303433645c75303433655c75303433315c75303433385c75323032365c222c5c22796561725c223a313939392c5c226167655265737472696374696f6e5c223a302c5c226469726563746f72735c223a5b5c2247656f726765204c756361735c225d2c5c226163746f72735c223a5b5c224d61726b2048616d696c6c5c222c5c224861727269736f6e20466f72645c222c5c22436172726965204669736865725c225d2c5c226475726174696f6e5c223a3131342c5c22636f756e74726965735c223a5b5c225553415c225d2c5c22726174696e675c223a7b5c226b696e6f706f69736b5c223a382e372c5c22696d64625c223a382e377d2c5c2273747265616d735c223a7b5c226d6f7669655c223a5c225c222c5c22747261696c65725c223a5c225c227d2c5c22636174616c6f67735c223a5b5d2c5c2264617465437265617465645c223a5c22323031342d31302d30315431323a30353a32342e3334385a5c222c5c22696d646249645c223a5c225c222c5c226b696e6f706f69736b49645c223a5c225c222c5c227075626c69736865645c223a66616c73652c5c227265636f6d6d656e645c223a747275652c5c226d6f64656c547970655c223a5c226d6f7669655c227d225d00000003181801");
```

**Comment by oleksiyk** [comment]
This patch should be correct. Actually these lines were present in my fork when I submitted my pull request back then (few months ago): https://github.com/oleksiyk/riakpbc/blob/master/lib/connection-manager.js#L96

**Comment by nlf** [comment]
Can you tell me what mapreduce query you're making that's causing you to see this? It may help me write a test for it.

**Comment by ahiipsa** [comment]
``` javascript
var request = {
        "inputs": "movies",
        "query": [
            {
                "map": {
                    "arg": "name",
                    "language": "erlang",
                    "module": "sortreduce",
                    "function": "get_field"
                }
            },
            {
                "reduce": {
                    "arg": {
                        "reduce_phase_only_1": true,
                        "bucket": "movies",
                        "offset": 1,
                        "limit": 30
                    },
                    "language": "erlang",
                    "module": "sortreduce",
                    "function": "sort_by_field"
                }
            },
            {
                "map": {
                    "language": "erlang",
                    "module": "sortreduce",
                    "function": "map_object_value"
                }
            }
        ]
    };  
```

**Comment by ahiipsa** [comment]
tcp dump

```
// Work
13:18:50.407906 IP RiakIP.8087 > 10.10.10.17.64045: Flags [.], seq 1:1449, ack 383, win 61, options [nop,nop,TS val 734641098 ecr 1161813322], length 1448
13:18:50.407910 IP RiakIP.8087 > 10.10.10.17.64045: Flags [P.], seq 1449:2240, ack 383, win 61, options [nop,nop,TS val 734641098 ecr 1161813322], length 791
13:18:50.407948 IP 10.10.10.17.64045 > RiakIP.8087: Flags [.], ack 2240, win 8095, options [nop,nop,TS val 1161813487 ecr 734641098], length 0
13:18:50.415675 IP RiakIP.8087 > 10.10.10.17.64045: Flags [P.], seq 2240:2247, ack 383, win 61, options [nop,nop,TS val 734641098 ecr 1161813322], length 7
13:18:50.415713 IP 10.10.10.17.64045 > RiakIP.8087: Flags [.], ack 2247, win 8191, options [nop,nop,TS val 1161813494 ecr 734641098], length 0

// Not work: net.Socket merge last 2 pocket to 1
13:17:27.382204 IP RiakIP.8087 > 192.168.2.149.63941: Flags [.], seq 1:1449, ack 383, win 61, options [nop,nop,TS val 734620349 ecr 1161731124], length 1448
13:17:27.382714 IP RiakIP.8087 > 192.168.2.149.63941: Flags [P.], seq 1449:2240, ack 383, win 61, options [nop,nop,TS val 734620349 ecr 1161731124], length 791
13:17:27.382717 IP RiakIP.8087 > 192.168.2.149.63941: Flags [P.], seq 2240:2247, ack 383, win 61, options [nop,nop,TS val 734620349 ecr 1161731124], length 7
13:17:27.382747 IP 192.168.2.149.63941 > RiakIP.8087: Flags [.], ack 2240, win 8142, options [nop,nop,TS val 1161731206 ecr 734620349], length 0
13:17:27.382770 IP 192.168.2.149.63941 > RiakIP.8087: Flags [.], ack 2247, win 8142, options [nop,nop,TS val 1161731206 ecr 734620349], length 0
```

**Comment by nlf** [comment]
I still can't figure out a test for this, so for now I just disabled coverage on these lines. Published in 2.0.3

**Comment by ahiipsa** [comment]
bug imitation

``` javascript
var RiakPBC = require('riakpbc'),
    singleMessages = [
        "000008bb18080212b5115b227b5c2269645c223a5c2231333632373837312d383731392d346631322d613331652d6463393935393631386431365c222c5c226e616d655c223a5c22315c75303431375c75303433325c75303433355c75303433375c75303433345c75303433645c75303434625c7530343335205c75303433325c75303433655c75303433395c75303433645c75303434623a205c75303432645c75303433665c75303433385c75303433375c75303433655c75303433342031205c7532303133205c75303432315c75303433615c75303434305c75303434625c75303434325c75303433305c7530343466205c75303434335c75303433335c75303434305c75303433655c75303433375c75303433305c222c5c226f726967696e4e616d655c223a5c225c222c5c2273686f727449645c223a302c5c226465736372697074696f6e5c223a5c225c75303431635c75303433385c75303434305c75303433645c75303433305c7530343466205c7530343338205c75303433665c75303434305c75303433655c75303434365c75303433325c75303433355c75303434325c75303433305c75303434655c75303434395c75303433305c7530343466205c75303433665c75303433625c75303433305c75303433645c75303433355c75303434325c7530343330205c75303431645c75303433305c75303433315c75303434332e205c75303432325c75303433655c75303434305c75303433335c75303433655c75303433325c75303433305c7530343466205c75303434345c75303433355c75303433345c75303433355c75303434305c75303433305c75303434365c75303433385c75303434662c205c75303433645c7530343335205c75303433365c75303433355c75303433625c75303433305c7530343466205c75303433665c75303433625c75303433305c75303434325c75303433385c75303434325c7530343463205c75303433645c75303433305c75303433625c75303433655c75303433335c75303433382c205c75303433325c75303434315c75303434325c75303434335c75303433665c75303433305c75303433355c7530343432205c7530343332205c75303433665c75303434305c75303434665c75303433635c75303433655c7530343339205c75303433615c75303433655c75303433645c75303434345c75303433625c75303433385c75303433615c7530343432205c7530343431205c75303433615c75303433655c75303434305c75303433655c75303433625c75303433355c75303433325c75303433655c7530343339205c75303431305c75303433635c75303433385c75303433345c75303433305c75303433625c75303433655c75303433392c205c75303433665c75303434305c75303433305c75303433325c75303434665c75303434395c75303433355c7530343339205c75303433645c7530343330205c75303433665c75303433625c75303433305c75303433645c75303433355c75303434325c75303433352c205c75303434375c75303434325c7530343365205c75303433665c75303434305c75303433385c75303433325c75303433655c75303433345c75303433385c7530343432205c7530343361205c75303433325c75303433655c75303433395c75303433645c75303433352e205c75303431645c7530343330205c75303434315c75303434325c75303433655c75303434305c75303433655c75303433645c7530343335205c75303433615c75303433655c75303434305c75303433655c75303433625c75303433355c75303433325c7530343462205c7530343338205c75303434305c75303433355c75303434315c75303433665c75303434335c75303433315c75303433625c75303433385c75303433615c7530343338205c7530343332205c75303433645c75303433355c7530343339205c75303434335c75303434375c75303433305c75303434315c75303434325c75303433325c75303434335c75303434655c7530343432205c75303433345c75303433325c7530343330205c75303434305c75303434625c75303434365c75303433305c75303434305c75303434662d5c75303433345c75303433365c75303433355c75303433345c75303433305c75303434663a205c75303434335c75303434375c75303433385c75303434325c75303433355c75303433625c7530343463205c7530343338205c75303434335c75303434375c75303433355c75303433645c75303433385c75303433612c205c75303431615c75303433325c75303433305c75303433392d5c75303431335c75303433655c75303433642d5c75303431345c75303433365c75303433385c7530343364205c7530343338205c75303431655c75303433315c75303433382d5c75303431325c75303433305c7530343364205c75303431615c75303433355c75303433645c75303433655c75303433315c75303433385c75323032365c222c5c22796561725c223a313939392c5c226167655265737472696374696f6e5c223a302c5c226469726563746f72735c223a5b5c2247656f726765204c756361735c225d2c5c226163746f72735c223a5b5c224d61726b2048616d696c6c5c222c5c224861727269736f6e20466f72645c222c5c22436172726965204669736865725c225d2c5c226475726174696f6e5c223a3131342c5c22636f756e74726965735c223a5b5c225553415c225d2c5c22726174696e675c223a7b5c226b696e6f706f69736b5c223a382e372c5c22696d64625c223a382e377d2c5c2273747265616d735c223a7b5c226d6f7669655c223a5c225c222c5c22747261696c65725c223a5c225c227d2c5c22636174616c6f67735c223a5b5d2c5c2264617465437265617465645c223a5c22323031342d31302d30315431323a30353a32342e3334385a5c222c5c22696d646249645c223a5c225c222c5c226b696e6f706f69736b49645c223a5c225c222c5c227075626c69736865645c223a66616c73652c5c227265636f6d6d656e645c223a747275652c5c226d6f64656c547970655c223a5c226d6f7669655c227d225d",
        "00000003181801"
    ],
    mergedMessages = [
        "000008bb18080212b5115b227b5c2269645c223a5c2231333632373837312d383731392d346631322d613331652d6463393935393631386431365c222c5c226e616d655c223a5c22315c75303431375c75303433325c75303433355c75303433375c75303433345c75303433645c75303434625c7530343335205c75303433325c75303433655c75303433395c75303433645c75303434623a205c75303432645c75303433665c75303433385c75303433375c75303433655c75303433342031205c7532303133205c75303432315c75303433615c75303434305c75303434625c75303434325c75303433305c7530343466205c75303434335c75303433335c75303434305c75303433655c75303433375c75303433305c222c5c226f726967696e4e616d655c223a5c225c222c5c2273686f727449645c223a302c5c226465736372697074696f6e5c223a5c225c75303431635c75303433385c75303434305c75303433645c75303433305c7530343466205c7530343338205c75303433665c75303434305c75303433655c75303434365c75303433325c75303433355c75303434325c75303433305c75303434655c75303434395c75303433305c7530343466205c75303433665c75303433625c75303433305c75303433645c75303433355c75303434325c7530343330205c75303431645c75303433305c75303433315c75303434332e205c75303432325c75303433655c75303434305c75303433335c75303433655c75303433325c75303433305c7530343466205c75303434345c75303433355c75303433345c75303433355c75303434305c75303433305c75303434365c75303433385c75303434662c205c75303433645c7530343335205c75303433365c75303433355c75303433625c75303433305c7530343466205c75303433665c75303433625c75303433305c75303434325c75303433385c75303434325c7530343463205c75303433645c75303433305c75303433625c75303433655c75303433335c75303433382c205c75303433325c75303434315c75303434325c75303434335c75303433665c75303433305c75303433355c7530343432205c7530343332205c75303433665c75303434305c75303434665c75303433635c75303433655c7530343339205c75303433615c75303433655c75303433645c75303434345c75303433625c75303433385c75303433615c7530343432205c7530343431205c75303433615c75303433655c75303434305c75303433655c75303433625c75303433355c75303433325c75303433655c7530343339205c75303431305c75303433635c75303433385c75303433345c75303433305c75303433625c75303433655c75303433392c205c75303433665c75303434305c75303433305c75303433325c75303434665c75303434395c75303433355c7530343339205c75303433645c7530343330205c75303433665c75303433625c75303433305c75303433645c75303433355c75303434325c75303433352c205c75303434375c75303434325c7530343365205c75303433665c75303434305c75303433385c75303433325c75303433655c75303433345c75303433385c7530343432205c7530343361205c75303433325c75303433655c75303433395c75303433645c75303433352e205c75303431645c7530343330205c75303434315c75303434325c75303433655c75303434305c75303433655c75303433645c7530343335205c75303433615c75303433655c75303434305c75303433655c75303433625c75303433355c75303433325c7530343462205c7530343338205c75303434305c75303433355c75303434315c75303433665c75303434335c75303433315c75303433625c75303433385c75303433615c7530343338205c7530343332205c75303433645c75303433355c7530343339205c75303434335c75303434375c75303433305c75303434315c75303434325c75",
        "303433325c75303434335c75303434655c7530343432205c75303433345c75303433325c7530343330205c75303434305c75303434625c75303434365c75303433305c75303434305c75303434662d5c75303433345c75303433365c75303433355c75303433345c75303433305c75303434663a205c75303434335c75303434375c75303433385c75303434325c75303433355c75303433625c7530343463205c7530343338205c75303434335c75303434375c75303433355c75303433645c75303433385c75303433612c205c75303431615c75303433325c75303433305c75303433392d5c75303431335c75303433655c75303433642d5c75303431345c75303433365c75303433385c7530343364205c7530343338205c75303431655c75303433315c75303433382d5c75303431325c75303433305c7530343364205c75303431615c75303433355c75303433645c75303433655c75303433315c75303433385c75323032365c222c5c22796561725c223a313939392c5c226167655265737472696374696f6e5c223a302c5c226469726563746f72735c223a5b5c2247656f726765204c756361735c225d2c5c226163746f72735c223a5b5c224d61726b2048616d696c6c5c222c5c224861727269736f6e20466f72645c222c5c22436172726965204669736865725c225d2c5c226475726174696f6e5c223a3131342c5c22636f756e74726965735c223a5b5c225553415c225d2c5c22726174696e675c223a7b5c226b696e6f706f69736b5c223a382e372c5c22696d64625c223a382e377d2c5c2273747265616d735c223a7b5c226d6f7669655c223a5c225c222c5c22747261696c65725c223a5c225c227d2c5c22636174616c6f67735c223a5b5d2c5c2264617465437265617465645c223a5c22323031342d31302d30315431323a30353a32342e3334385a5c222c5c22696d646249645c223a5c225c222c5c226b696e6f706f69736b49645c223a5c225c222c5c227075626c69736865645c223a66616c73652c5c227265636f6d6d656e645c223a747275652c5c226d6f64656c547970655c223a5c226d6f7669655c227d225d00000003181801"
    ],
    port = 8124,
    messages = mergedMessages,
    sleep = function(millis, callback) {
        setTimeout(function() {
            callback();
        }, millis);
    },
    sendMessage = function(connection, messages, n) {
        sleep(1000 * n, function() {
            var buffer = new Buffer(new Buffer(messages[n], 'hex'));
            connection.write(buffer);
        });
    };

net.createServer(function(connection) {
        connection.on('data', function(data) {
            for(var i = 0; i < messages.length; i++){
                sendMessage(connection, messages, i);
            }
        });
}).listen(port);

var client = RiakPBC.createClient({port: port});

client.mapred({}, function (err, result) {
    console.log('end');
});
```

**Pull request merged**
