### PR TITLE
Tweaktown

### PR DESCRIPTION
**Pull request by nlf**
So this makes the queue actually asynchronous, which prevents random hangs when a callback function throws. It also simplified the `_processMessage` function a bit, which is nice.

Testing has been switched to use [lab](https://github.com/spumko/lab) since it gives the added benefit of being able to very easily test for code coverage. And it's what I'm more familiar with.

### CODE REVIEW

**Comment by oleksiyk** [comment]
Can you please clarify on queue hangups with exceptions thrown in callback? This code:

``` javascript
setImmediate(this._processNext.bind(this));
```

Has huge performance impact...

**Comment by nlf** [comment]
The way `_processNext` was being called before was actually synchronous, so what could happen in some cases (specifically, when using domains) is if your callback threw an error, the next line of code would never execute, which means the current task was never being removed from the queue and so all future calls would never respond since the client believed a task was already being processed.

It was a big cascading failure with horrible results. You can try using `process.nextTick` instead of `setImmediate` and see if that improves performance. If it does, I'll swap them around. The difference is `setImmediate` yields for i/o while `process.nextTick` does not.

**Comment by oleksiyk** [comment]
Why not call callback in setImmediate instead?

**Comment by nlf** [comment]
Because if you do it that way, we have a race condition where the task could be destroyed before the callback is fired. I tested, it didn't resolve the issue with the queue not progressing also.

**Pull request merged**
